version: "3"
services:
  web-login:
    build:
     context: .
     dockerfile: ./Docker/login/Dockerfile
    ports: ["8080:8880"]
    volumes: [./PPD_app:/PPD_app]
    environment:
      FLASK_ENV: development
      LOGIN_JWT_SECRET: $LOGIN_JWT_SECRET
  web-files:
    build:
     context: .
     dockerfile: ./Docker/files/Dockerfile
    ports: ["8081:8881"]
    volumes: [./PPD_app:/PPD_app]
    environment:
      FLASK_ENV: development
      LOGIN_JWT_SECRET: $LOGIN_JWT_SECRET
  web-plocker:
    build:
     context: .
     dockerfile: ./Docker/parcel_locker/Dockerfile
    ports: ["8082:8882"]
    volumes: [./PPD_app:/PPD_app]
    environment:
      FLASK_ENV: development
      COURIER_JWT_SECRET: $COURIER_JWT_SECRET
  web-courier:
    build:
     context: .
     dockerfile: ./Docker/courier/Dockerfile
    ports: ["8083:8883"]
    volumes: [./PPD_app:/PPD_app]
    environment:
      FLASK_ENV: development
      COURIER_JWT_SECRET: $COURIER_JWT_SECRET
  redis-db:
    image: "redis:alpine"
